### ISSUE TITLE
Notification System

### ISSUE THREAD

**Issue by the-y9** [the-y9/SE-Project#10]
@AyushV-21f3 
Select Recipients in the Notification System is selecting students one at a time. It will be inefficient.
![image](https://github.com/user-attachments/assets/487b27d6-36c5-4e1e-9ae8-9062b454c781)

**Comment by shukla-nitish** [comment]
okay, will change it for teams. Recipients will be students of a team

**Comment by SaarthakS98** [comment]
Made the changes for it in the models. Pending for frontend.

**Comment by shukla-nitish** [comment]
Notification was enabled for individual students and for a team.
